/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */

plugins {
    kotlin("jvm") version "1.9.22"
    id("com.github.johnrengelman.shadow") version "8.1.1"
    `maven-publish`
}

group = "dev.alta"
version = "1.0.0"

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://oss.sonatype.org/content/repositories/snapshots/")
    maven("https://repo.lucko.me/")
    maven("https://repo.aikar.co/content/groups/aikar/")
}

dependencies {
    // Kotlin
    implementation(kotlin("stdlib"))
    
    // Paper API
    compileOnly("io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT")
    
    // LuckPerms
    compileOnly("net.luckperms:api:5.4")
    
    // Helper
    implementation("me.lucko:helper:5.6.13") {
        exclude(group = "com.google.guava")
    }
    
    // MongoDB
    implementation("org.mongodb:mongodb-driver-sync:4.11.1")
    
    // ACF Paper
    api("co.aikar:acf-paper:0.5.1-SNAPSHOT")
    
    // Reflections
    implementation("org.reflections:reflections:0.10.2")
    
    // Adventure
    implementation("net.kyori:adventure-api:4.15.0")
    implementation("net.kyori:adventure-text-minimessage:4.15.0")
    implementation("net.kyori:adventure-platform-bukkit:4.3.2")
    
    // Redis (Lettuce)
    implementation("io.lettuce:lettuce-core:6.3.0.RELEASE")
}

tasks {
    // Disable the default JAR task
    jar {
        enabled = false
    }
    
    // Make build depend on shadowJar
    build {
        dependsOn(shadowJar)
    }
    
    shadowJar {
        archiveBaseName.set("Essentials")
        archiveClassifier.set("")
        archiveVersion.set("")
        
        relocate("me.lucko.helper", "dev.alta.essentials.libs.helper")
        relocate("co.aikar.commands", "dev.alta.essentials.libs.acf")
        relocate("org.reflections", "dev.alta.essentials.libs.reflections")
        
        mergeServiceFiles()
        exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA")
    }
    
    processResources {
        filesMatching("plugin.yml") {
            expand(project.properties)
        }
    }
    
    compileKotlin {
        kotlinOptions.jvmTarget = "17"
    }
    
    compileJava {
        options.release.set(17)
    }
    
    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "dev.alta"
            artifactId = "essentials"
            version = "1.0.0"
            
            artifact(tasks.shadowJar)
        }
    }
}
